# Generated by Django 6.0.5 on 2026-05-14 05:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('parking_name', models.CharField(max_length=200)),
                ('google_map_link', models.URLField()),
                ('address', models.TextField()),
                ('price_per_hour', models.IntegerField()),
                ('govt_id', models.ImageField(upload_to=accounts.models.govt_id_upload_path)),
                ('parking_image', models.ImageField(upload_to=accounts.models.parking_image_upload_path)),
                ('parking_document', models.FileField(upload_to=accounts.models.document_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=30)),
            ],
        ),
    ]
