# Generated by Django 6.0.5 on 2026-05-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerregister',
            name='status',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
