# Generated by Django 6.0.5 on 2026-05-17 15:52

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ownerregister_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerregister',
            name='parking_document',
        ),
        migrations.RemoveField(
            model_name='ownerregister',
            name='parking_image',
        ),
        migrations.CreateModel(
            name='ParkingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to=accounts.models.document_upload_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_documents', to='accounts.ownerregister')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.parking_image_upload_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_images', to='accounts.ownerregister')),
            ],
        ),
    ]
